// success
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_PRODUCT_BY_ID  = "GET_PRODUCT_BY_ID";
// fail
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";